### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by kamranisbest** [ryanckulp/product_hunt_upvotes#1]
Hi, 
  On using URL it returns empty and does nothing. Can you please check and update why its not working. Feel free to contact me for further details.

Thanks :)

**Comment by ryanckulp** [comment]
hey @kamranisbest, i just tried on my side and it works OK.

are you providing both:

a) your dev token (not api key/secret)
b) a root URL, to a product that's been hunted?

perhaps B) is a bit confusing... this should be a url like this:
http://generator.persistiq.com/

(because [that product](https://www.producthunt.com/posts/cold-email-generator), with that url, has been hunted)

**Comment by kamranisbest** [comment]
Hi ,

   Thanks for quick response. Can you please help me with this as if we have url like https://www.producthunt.com/posts/cold-email-generator as you provided of a product how we can get subdomain based url of that product. Feel free to contact with me for further details.

Thanks :)

**Comment by ryanckulp** [comment]
sure thing. simply visit the product hunt page, click 'get this', and use
that url. it's not about a subdomain per se, just use the product's actual
URL that was hunted.

ryan kulp
blog - kulp.me

**Comment by kamranisbest** [comment]
Hi,

   Yes sure thanks i will try that and will update you. Really appreciate your help :)

Thanks :)
